### ISSUE TITLE
Next image feature

### ISSUE THREAD

**Issue by aletss** [Quiroptero/monocromo.py#1]
Hello!

Just a suggestion (I don't know how hard is this to be implemented): after clicking a photo, I tried to go to the next one pressing the right arrow, and since it didn't work, I tried to see if there was an arrow at the right of the image (similar to instagram) but there wasn't that either. Could be a good feature :)

**Comment by Quiroptero** [comment]
I like the idea of going to the previous/next image using the back/forward arrows. As of today I don't know how to do that, tho :sweat_smile:. I'll investigate on the matter and implement it, if possible.

Thanks for the suggestion!

**Comment by Quiroptero** [comment]
Hi @aletss. Long time no see. After some thinking I've decided not to implement this feature. I like the idea of having a website that feels simple, almost _archaic_. I haven't even made an About page for it. Each photo page has already a couple of navigation links at the bottom and for now that suits my needs the best.

However, here's how I would do it if I were to implement the feature. 

I'd bind the `accesskey` attribute of an otherwise empty HTML tag to a specific key, say K for next and J for previous photos. Upon pressing the combination `[Alt] + accesskey` ([in almost all browsers](https://www.w3schools.com/TAGS/att_accesskey.asp)) a javascript method gets called. Such method performs the navigation by changing the `href` of the current location. Something like the following:

```html
<a id="next-photo" accesskey="k" title="(Alt + K)">
<a id="prev-photo" accesskey="j" title="(Alt + J)">
```

```javascript
    document.getElementById('next-photo').addEventListener('click', function(event) {
      window.location.href = "<URL of next photo>";
    });

    document.getElementById('prev-photo').addEventListener('click', function(event) {
      window.location.href = "<URL of previous photo>";
    });
```

I have an actual example [here](https://github.com/Quiroptero/paperbat/blob/master/layouts/partials/header.html#L148) and [here](https://github.com/Quiroptero/paperbat/blob/master/layouts/partials/random_bat.html).
